Restructure/Reformat
zegami/zegami-python-sdk pull request #91
Opened 2022-03-09 13:00 UTC by Vaspra

- No longer uses Collection, CollectionV2, or a `_construct_collection` method.
- All methods in the regular Collection class support V1/V2, filling in gaps from before this change
- `get_annotations` now works consistently and returns a list of annotations, no more searching through sources or having to dig into the results `['annotations']`
- Cut down and simplified unnecessary code for fetching various _data entries and redundant checks.
- Moved a couple of methods orders around (keeping __repr__, __len__ at top, etc.)
- Docstring/formatting

Tested getting annotations from V1 and V2 collections, works now as it didn't before. **Very likely that tests need to be updated.**

2022-03-09 13:12 UTC, ahaith commented
Generally looks sensible, although I tend to feel all the little styling changes are unnecessary and get in the way of seeing the important changes (both in the PR diff, and when looking through history in the future)

Clearly a few risks here, so I feel we should probably get out a stable SDK release before merging this one then take a bit more time to address e2e tests etc..

2022-03-09 13:39 UTC, Vaspra commented
Fair points, I would argue that the prior state was not "stable" in terms of annotations API though. Perhaps the best way forward would be to temporarily point the serverless at this branch for testing over the next couple of days, and the team can have time to review/test this.

2022-03-16 16:24 UTC, ahaith requested changes
Mostly looks great.

Running the e2e tests revealed one error: `delete_all_annotations` needs updating to handle the new shape coming out of `get_annotations`

I've put up a PR to update the tests for some other tests which failed because they expected the old shape, but this new shape is definitely superior. (https://github.com/zegami/zegami-ship/pull/968)

2022-03-16 16:25 UTC, ahaith commented on zegami_sdk/collection.py
> +        return annos['annotations']
https://github.com/zegami/zegami-ship/pull/968

2022-03-17 11:27 UTC, Vaspra commented on zegami_sdk/collection.py
> +                for k, v in a['metadata'].items():
I agree for `metadata` hence the optional but the others are core to the annotation schema. If the schema changes I think throwing a `KeyError` is better than skipping, and we can update as needed.

2022-03-17 11:32 UTC, Vaspra commented on zegami_sdk/collection.py
> +        return annos['annotations']
Excellent thanks, this was a huge pain as the different collection versions returned different formats with required extra steps,

2022-03-17 13:44 UTC, ahaith approved these changes
e2e sdk tests pass with this code (and the associated updates), so happy for this to be merged.

2022-03-18 13:44 UTC, merged